source( "R/data_retrieval.R" )
source( "R/quality_control.R" )
source( "R/preprocess.R" )
dataset <- "GSE64415"
print( "Retrieving dataset" )
setwd( file.path( "data", "rawData" ))
get.raw.data( dataset )
setwd( dataset )
geo.data <- unpack.data()
chipType <- cdfName( geo.data )
print(" Unfiltered samples: " )
print( geo.data )
print( list.celfiles() )
aqm.results <- generateAQM( geo.data )
filter.data( aqm.results )
print( "Filtered samples: " )
print( list.celfiles() )
setwd( "../../.." )
preprocessed.data <- preprocess( dataset, chipType )

