source( "get_data.R" )
source( "quality_control.R" )
setwd(file.path( "..", "data", "GSE64415" ))
#get.data( "GSE64415 ")
geo.data <- unpack.data()
print(" Unfiltered: " )
print( geo.data )
print( sampleNames( geo.data ) )
aqm.results <- generateAQM( geo.data )
filtered.data <- filter.marrays( aqm.results )
print( "Filtered: " )
print( filtered.data )
print( sampleNames( filtered.data ) )
