library( affy )
library( arrayQualityMetrics )

generateAQM <- function() {
    out.file <- file.path( "/.mounts/labs/reimandlab/private/users/nsiddiqui/R", "AQM.RData" )
    print( "Read in raw data as AffyBatch object." )
    affy.data <- ReadAffy()
    m <- list()
    print("Preparing data for summary statistics.")
    x <- prepdata( affy.data, intgroup = c(), do.logtransform = TRUE )
    pdf( tempfile() )
    print( "Generating array quality metrics." )
    print( "Heatmap" )
    m$heatmap <- aqm.heatmap( x )
    print("PCA")
    m$pca <- aqm.pca( x )
    print( "Boxplot" )
    m$boxplot <- aqm.boxplot( x )
    print( "Density" )
    m$density <- aqm.density( x )
    print( "Meansd" )
    m$meansd <- aqm.meansd( x )
    print( "Probesmap" )
    m$probesmap <- aqm.probesmap( x )
    print( "Preparing data to perform Affymetrix-specific quality metrics." )
    x <- prepaffy( affy.data, x )
    print( "Generating Affymetrix-specific array quality metrics." )
    print( "RLE" )
    m$rle <- aqm.rle( x )
    print( "NUSE" )
    m$nuse <- aqm.nuse( x )
    print( "RNAdeg" )
    m$rnadeg <- aqm.rnadeg( affy.data, x )
    print( "PMMM" )
    m$pmmm <- aqm.pmmm( x )
    print( "MAplot" )
    m$maplot = aqm.maplot( x )
    grDevices::dev.off()
    print( "Saving AQM object." ) 
    save( m, file = out.file )
    print( "done." )
}
