library( affy )
library( arrayQualityMetrics )

generateAQM <- function( marray_data ) {
    print("Performing generateAQM function...")
    out.file <- file.path( "..", "..", "output", "AQM.RData" )
    m <- list()
    print("Preparing data for summary statistics.")
    x <- prepdata( marray_data, intgroup = c(), do.logtransform = TRUE )
    pdf( tempfile() )
    print("Generating array quality metrics...")
    m$heatmap <- aqm.heatmap( x )
    m$pca <- aqm.pca( x )
    m$boxplot <- aqm.boxplot( x )
    m$density <- aqm.density( x )
    m$meansd <- aqm.meansd( x )
    m$probesmap <- aqm.probesmap( x )
    print("Preparing data to perform Affymetrix-specific quality metrics...")
    x <- prepaffy( marray_data, x )
    print("Generating Affymetrix-specific array quality metrics...")
    m$rle <- aqm.rle(x)
    m$nuse <- aqm.nuse(x)
    m$rnadeg <- aqm.rnadeg(gse.data, x)
    m$pmmm <- aqm.pmmm(x)
    m$maplot = aqm.maplot(x)
    grDevices::dev.off()
    save( m, file = out.file )
}
